artifacts_root: artifacts

#config for data ingestion pipeline
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/aman1290/scrapedcardata/raw/refs/heads/main/dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


#config for data validation pipeline

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/dataset/shuffled_cleaned_car_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

#config for data transformation pipeline

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/dataset/shuffled_cleaned_car_data.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json






